all:
	gcc list_interface.c -o list_interface.out
	gcc get_info.c -o get_info.out
	gcc get_wireless_signal.c -o get_wireless_signal.out
	gcc get_ssid.c -o get_ssid.out
	gcc get_apmode.c -o get_apmode.out

clean:
	rm -rf *.out
